name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MoonBit
      uses: moonbitlang/setup-moonbit@v1
      
    - name: Check moon version
      run: moon version
      
    - name: Moon check
      run: moon check
      
    - name: Run tests
      run: moon test
      
    - name: Build package
      run: moon build
      
    - name: Generate docs
      run: moon doc

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MoonBit
      uses: moonbitlang/setup-moonbit@v1
      
    - name: Run tests with coverage
      run: moon test --enable-coverage
      
    - name: Generate coverage report
      run: moon coverage report

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MoonBit
      uses: moonbitlang/setup-moonbit@v1
      
    - name: Check formatting
      run: moon fmt --check

  matrix-test:
    name: Matrix Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MoonBit
      uses: moonbitlang/setup-moonbit@v1
      
    - name: Run tests
      run: moon test
      
    - name: Build package
      run: moon build